version: '3.1'

services:
  pet_shelter:
    build: .
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

